// <auto-generated />
namespace AirTicketsService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_flightID_to_TicketMoDel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_flightID_to_TicketMoDel));
        
        string IMigrationMetadata.Id
        {
            get { return "201708070853360_Added_flightID_to_TicketMoDel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
