// <auto-generated />
namespace AirTicketsService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Deleted_retrun_and_direct_tickets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deleted_retrun_and_direct_tickets));
        
        string IMigrationMetadata.Id
        {
            get { return "201709091413326_Deleted_retrun_and_direct_tickets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
